In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("..\\data\\airline_2m.csv" , encoding="latin-1")
df.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum
0,1998,1,1,2,5,1998-01-02,NW,19386,NW,N297US,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2009,2,5,28,4,2009-05-28,FL,20437,FL,N946AT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013,2,6,29,6,2013-06-29,MQ,20398,MQ,N665MQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,3,8,31,2,2010-08-31,DL,19790,DL,N6705Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2006,1,1,15,7,2006-01-15,US,20355,US,N504AU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.columns

Index(['Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek', 'FlightDate',
       'Reporting_Airline', 'DOT_ID_Reporting_Airline',
       'IATA_CODE_Reporting_Airline', 'Tail_Number',
       ...
       'Div4WheelsOff', 'Div4TailNum', 'Div5Airport', 'Div5AirportID',
       'Div5AirportSeqID', 'Div5WheelsOn', 'Div5TotalGTime',
       'Div5LongestGTime', 'Div5WheelsOff', 'Div5TailNum'],
      dtype='object', length=109)

In [4]:
threshold = 0.45

df = df.loc[:, df.isna().mean() <= threshold]

In [5]:
df.columns

Index(['Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek', 'FlightDate',
       'Reporting_Airline', 'DOT_ID_Reporting_Airline',
       'IATA_CODE_Reporting_Airline', 'Tail_Number',
       'Flight_Number_Reporting_Airline', 'OriginAirportID',
       'OriginAirportSeqID', 'OriginCityMarketID', 'Origin', 'OriginCityName',
       'OriginState', 'OriginStateFips', 'OriginStateName', 'OriginWac',
       'DestAirportID', 'DestAirportSeqID', 'DestCityMarketID', 'Dest',
       'DestCityName', 'DestState', 'DestStateFips', 'DestStateName',
       'DestWac', 'CRSDepTime', 'DepTime', 'DepDelay', 'DepDelayMinutes',
       'DepDel15', 'DepartureDelayGroups', 'DepTimeBlk', 'TaxiOut',
       'WheelsOff', 'WheelsOn', 'TaxiIn', 'CRSArrTime', 'ArrTime', 'ArrDelay',
       'ArrDelayMinutes', 'ArrDel15', 'ArrivalDelayGroups', 'ArrTimeBlk',
       'Cancelled', 'Diverted', 'CRSElapsedTime', 'ActualElapsedTime',
       'AirTime', 'Flights', 'Distance', 'DistanceGroup'],
      dtype='object')

In [6]:
df = df[['Year', 'Month', 'DayofMonth', 'DayOfWeek','CRSDepTime','CRSArrTime','CRSElapsedTime','DepTimeBlk','Origin','Dest','Distance','Reporting_Airline','Tail_Number','ArrDel15']]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 14 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   CRSDepTime         int64
 5   CRSArrTime         int64
 6   CRSElapsedTime     float64
 7   DepTimeBlk         object
 8   Origin             object
 9   Dest               object
 10  Distance           float64
 11  Reporting_Airline  object
 12  Tail_Number        object
 13  ArrDel15           float64
dtypes: float64(3), int64(6), object(5)
memory usage: 213.6+ MB

In [8]:
df = (df[df["Year"] >= 2000])

In [9]:
df.isna().sum()

Year                     0
Month                    0
DayofMonth               0
DayOfWeek                0
CRSDepTime               0
CRSArrTime               0
CRSElapsedTime          28
DepTimeBlk               0
Origin                   0
Dest                     0
Distance                 0
Reporting_Airline        0
Tail_Number           8060
ArrDel15             28705
dtype: int64

In [10]:
df.dropna(subset=['ArrDel15'], inplace=True)

In [11]:
df.isna().sum()

Year                  0
Month                 0
DayofMonth            0
DayOfWeek             0
CRSDepTime            0
CRSArrTime            0
CRSElapsedTime        0
DepTimeBlk            0
Origin                0
Dest                  0
Distance              0
Reporting_Airline     0
Tail_Number          10
ArrDel15              0
dtype: int64

In [12]:
df.dropna(subset=['Tail_Number'], inplace=True)

In [13]:
target = df[['ArrDel15']]

In [14]:
data = df.drop("ArrDel15",axis=1)

In [15]:
print(data.shape)
print(target.shape)

(1310295, 13)
(1310295, 1)

In [16]:
data.head()

,Year,Month,DayofMonth,DayOfWeek,CRSDepTime,CRSArrTime,CRSElapsedTime,DepTimeBlk,Origin,Dest,Distance,Reporting_Airline,Tail_Number
1,2009,5,28,4,1204,1541,157.0,1200-1259,MKE,MCO,1066.0,FL,N946AT
2,2013,6,29,6,1630,1945,135.0,1600-1659,GJT,DFW,773.0,MQ,N665MQ
3,2010,8,31,2,1305,2035,270.0,1300-1359,LAX,DTW,1979.0,DL,N6705Y
4,2006,1,15,7,1820,2026,126.0,1800-1859,EWR,CLT,529.0,US,N504AU
6,2006,8,7,1,1755,2000,125.0,1700-1759,BOS,CLE,563.0,CO,N27724

In [17]:
data.to_csv("..\\data\\data.csv" ,index = False)
target.to_csv("..\\data\\target.csv", index=False)