In [1]:
import numpy as np
import pandas as pd

In [ ]:
df =  pd.read_excel("..\\data\\raw\\MID.xlsx")

In [3]:
df.head()

,Name,Link,Contains,ProductIntroduction,ProductUses,ProductBenefits,SideEffect,HowToUse,HowWorks,QuickTips,SafetyAdvice,Chemical_Class,Habit_Forming,Therapeutic_Class,Action_Class
0,Andol 0.5mg Tablet,https://www.1mg.com/drugs/andol-0.5mg-tablet-6...,Haloperidol (0.5mg),Andol 0.5mg Tablet can also be used for treati...,"\n \n \nul \""\""\n\n \n 0\n\n \n Schiz...",\n \n Schizophrenia \n \n Schizophrenia is ...,Most side effects do not require any medical a...,Take this medicine in the dose and duration as...,Andol 0.5mg Tablet is a typical antipsychotic....,\n \n Andol 0.5mg Tablet helps treat schizop...,"\nAlcohol\n,\nAndol 0.5mg Tablet may cause exc...",Butyrophenone Derivative,No,NEURO CNS,Typical Antipsychotic
1,Avastin 100mg Injection,https://www.1mg.com/drugs/avastin-100mg-inject...,Bevacizumab (100mg),"\np dir=\""ltr\"" style=\""line-height: 1.38; mar...","\n \n \nul \""\""\n\n \n 0\n\n \n Cance...",\n \n Cancer of colon and rectum \n \n Canc...,Most side effects do not require any medical a...,Your doctor or nurse will give you this medici...,Avastin 100mg Injection is a anti-angiogenic m...,\n \n Avastin 100mg Injection is an effectiv...,"\nAlcohol\n,\nIt is not known whether it is sa...",Monoclonal antibody (mAb),No,ANTI NEOPLASTICS,Vascular endothelial growth factor (VEGF) in...
2,Actorise 40 Injection,https://www.1mg.com/drugs/actorise-40-injectio...,Darbepoetin alfa (40mcg),Actorise 40 Injection is a medicine that needs...,"\n \n \nul \""\""\n\n \n 0\n\n \n Treat...",\n \n Treatment of Anemia due to chronic kid...,Most side effects do not require any medical a...,Your doctor or nurse will give you this medici...,Actorise 40 Injection is an erythropoiesis-sti...,\n \n Actorise 40 Injection helps in the tre...,"\nAlcohol\n,\nIt is not known whether it is sa...","Amino Acids, Peptides Analogues",No,BLOOD RELATED,Erythropoiesis-stimulating agent (ESA
3,Actorise 25 Injection,https://www.1mg.com/drugs/actorise-25-injectio...,Darbepoetin alfa (25mcg),Actorise 25 Injection is a medicine that needs...,"\n \n \nul \""\""\n\n \n 0\n\n \n Treat...",\n \n Treatment of Anemia due to chronic kid...,Most side effects do not require any medical a...,Your doctor or nurse will give you this medici...,Actorise 25 Injection is an erythropoiesis-sti...,\n \n Actorise 25 Injection helps in the tre...,"\nAlcohol\n,\nIt is not known whether it is sa...","Amino Acids, Peptides Analogues",No,BLOOD RELATED,Erythropoiesis-stimulating agent (ESA
4,Actorise 60 Injection,https://www.1mg.com/drugs/actorise-60-injectio...,Darbepoetin alfa (60mcg),Actorise 60 Injection is a medicine that needs...,"\n \n \nul \""\""\n\n \n 0\n\n \n Treat...",\n \n Treatment of Anemia due to chronic kid...,Most side effects do not require any medical a...,Your doctor or nurse will give you this medici...,Actorise 60 Injection is an erythropoiesis-sti...,\n \n Actorise 60 Injection helps in the tre...,"\nAlcohol\n,\nIt is not known whether it is sa...","Amino Acids, Peptides Analogues",No,BLOOD RELATED,Erythropoiesis-stimulating agent (ESA

In [4]:
df.isna().sum()

Name                        0
Link                        0
Contains                    0
ProductIntroduction     11986
ProductUses                 0
ProductBenefits             0
SideEffect                  0
HowToUse                   95
HowWorks                  236
QuickTips                   0
SafetyAdvice                0
Chemical_Class          91334
Habit_Forming               0
Therapeutic_Class           0
Action_Class           107117
dtype: int64

In [5]:
df.columns

Index(['Name', 'Link', 'Contains', 'ProductIntroduction', 'ProductUses',
       'ProductBenefits', 'SideEffect', 'HowToUse', 'HowWorks', 'QuickTips',
       'SafetyAdvice', 'Chemical_Class', 'Habit_Forming', 'Therapeutic_Class',
       'Action_Class'],
      dtype='object')

In [6]:
df["id"] = range(1, len(df) + 1)

In [7]:
df = df[["id",'Contains','SideEffect','Chemical_Class', 'Habit_Forming','Therapeutic_Class']]

In [8]:
df.head()

,id,Contains,SideEffect,Chemical_Class,Habit_Forming,Therapeutic_Class
0,1,Haloperidol (0.5mg),Most side effects do not require any medical a...,Butyrophenone Derivative,No,NEURO CNS
1,2,Bevacizumab (100mg),Most side effects do not require any medical a...,Monoclonal antibody (mAb),No,ANTI NEOPLASTICS
2,3,Darbepoetin alfa (40mcg),Most side effects do not require any medical a...,"Amino Acids, Peptides Analogues",No,BLOOD RELATED
3,4,Darbepoetin alfa (25mcg),Most side effects do not require any medical a...,"Amino Acids, Peptides Analogues",No,BLOOD RELATED
4,5,Darbepoetin alfa (60mcg),Most side effects do not require any medical a...,"Amino Acids, Peptides Analogues",No,BLOOD RELATED

In [ ]:
df.to_csv("..\\data\\processed\\dataset.csv",index=False)