In [89]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
ingredients =  pd.read_csv("..\\data\\processed\\ingredients.csv")

In [ ]:
sideeffects =  pd.read_csv("..\\data\\processed\\sideeffects.csv")

In [ ]:
og_data = pd.read_csv("..\\data\\processed\\dataset.csv")

In [93]:
og_data.columns

Index(['id', 'Contains', 'SideEffect', 'Chemical_Class', 'Habit_Forming',
       'Therapeutic_Class'],
      dtype='object')

In [94]:
og_data = og_data[['id','Chemical_Class', 'Habit_Forming','Therapeutic_Class']]

In [95]:
og_data.head()

   id                      Chemical_Class Habit_Forming    Therapeutic_Class
0   1           Butyrophenone Derivative            No            NEURO CNS
1   2          Monoclonal antibody (mAb)            No     ANTI NEOPLASTICS
2   3    Amino Acids, Peptides Analogues            No        BLOOD RELATED
3   4    Amino Acids, Peptides Analogues            No        BLOOD RELATED
4   5    Amino Acids, Peptides Analogues            No        BLOOD RELATED

In [96]:
ingredients.columns

Index(['id', 'ingredients_mapped'], dtype='object')

In [97]:
sideeffects.columns

Index(['id', 'side_mapped'], dtype='object')

In [98]:
df = og_data.merge(ingredients, how='inner', on='id') \
            .merge(sideeffects, how='inner', on='id')

In [99]:
df.columns

Index(['id', 'Chemical_Class', 'Habit_Forming', 'Therapeutic_Class',
       'ingredients_mapped', 'side_mapped'],
      dtype='object')

In [100]:
df.head()

,id,Chemical_Class,Habit_Forming,Therapeutic_Class,ingredients_mapped,side_mapped
0,1,Butyrophenone Derivative,No,NEURO CNS,Haloperidol,agitation ## movement disorder ## sleep distur...
1,2,Monoclonal antibody (mAb),No,ANTI NEOPLASTICS,Bevacizumab,bleeding ## taste changes ## headache ## back ...
2,3,"Amino Acids, Peptides Analogues",No,BLOOD RELATED,Darbepoetin alfa,abdominal pain ## high blood pressure ## skin ...
3,4,"Amino Acids, Peptides Analogues",No,BLOOD RELATED,Darbepoetin alfa,abdominal pain ## high blood pressure ## skin ...
4,5,"Amino Acids, Peptides Analogues",No,BLOOD RELATED,Darbepoetin alfa,abdominal pain ## high blood pressure ## skin ...

In [101]:
df = df[['id','Chemical_Class', 'Habit_Forming','Therapeutic_Class','ingredients_mapped','side_mapped']]

In [ ]:
df.to_csv("..\\data\\processed\\ml-data.csv",index=False)